### ISSUE TITLE
StackOverflowError occured with out-parameter of service

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#123]
I've defined a service which has an out-parameter `<parameter name="errorString"/>`
when assign this param a GroovyString with an expression with `context`
```xml
<set field="errorString" value="Errors context:${context}"/>
```
Error occurred when I access to this out-parameter after complete service call

```
<service-call name="problematicService" in-map="context" out-map="context"/>
<log level="info" message="*** After call service errorString: ${errorString}"/>
```

Exception stack:
```java
java.lang.StackOverflowError
        at groovy.lang.MetaClassImpl.getMethodWithCaching(MetaClassImpl.java:1288) ~[groovy-2.4.7.jar:2.4.7]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1062) ~[groovy-2.4.7.jar:2.4.7]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024) ~[groovy-2.4.7.jar:2.4.7]
        at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:581) ~[groovy-2.4.7.jar:2.4.7]
        at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:575) ~[groovy-2.4.7.jar:2.4.7]
        at org.codehaus.groovy.runtime.InvokerHelper.toString(InvokerHelper.java:130) ~[groovy-2.4.7.jar:2.4.7]
        at org.codehaus.groovy.runtime.InvokerHelper.write(InvokerHelper.java:527) ~[groovy-2.4.7.jar:2.4.7]
        at groovy.lang.GString.writeTo(GString.java:183) ~[groovy-2.4.7.jar:2.4.7]
        at groovy.lang.GString.toString(GString.java:155) ~[groovy-2.4.7.jar:2.4.7]
        at org.codehaus.groovy.runtime.typehandling.ShortTypeHandling.castToString(ShortTypeHandling.java:45) ~[groovy-2.4.7.jar:2.4.7]
        at org.moqui.impl.entity.EntityFindBase.toString(EntityFindBase.groovy:695) ~[moqui-framework-2.0.0.jar:2.0.0]
        at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:628) ~[groovy-2.4.7.jar:2.4.7]
        at org.codehaus.groovy.runtime.InvokerHelper.formatMap(InvokerHelper.java:663) ~[groovy-2.4.7.jar:2.4.7]
        at org.codehaus.groovy.runtime.InvokerHelper.toMapString(InvokerHelper.java:752) ~[groovy-2.4.7.jar:2.4.7]
        at org.codehaus.groovy.runtime.InvokerHelper.toMapString(InvokerHelper.java:741) ~[groovy-2.4.7.jar:2.4.7]
        at org.codehaus.groovy.runtime.InvokerHelper.write(InvokerHelper.java:506) ~[groovy-2.4.7.jar:2.4.7]
        ...
        at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:628) ~[groovy-2.4.7.jar:2.4.7]
    15:39:17.158  WARN  Test worker      o.moqui.i.c.TransactionFacadeImpl Transaction rollback. The rollback was originally caused by: Error running service pointshub.PHPointServices.create#EntireOrderPointCalculation (Throwable)
    java.lang.StackOverflowError
        at java.util.HashMap.hash(HashMap.java:338) ~[?:1.8.0_60]
        at java.util.HashMap.put(HashMap.java:611) ~[?:1.8.0_60]
        at java.util.HashSet.add(HashSet.java:219) ~[?:1.8.0_60]
        at org.moqui.impl.entity.EntityValueBase.entrySet(EntityValueBase.java:1102) ~[moqui-framework-2.0.0.jar:2.0.0]
```
Maybe the problem is using `context` in GroovyString assigned to out-param. In this case, it's better if there's some explicit exception similar to when we try to set variable `context`.

**Comment by jonesde** [comment]
That is handled by low-level Groovy code, not something we have much control over or can intercept. The problem is the Groovy string expansion, and in general treating an Object like a string like in that case with the context, Groovy does it's own to String stuff instead of calling the Object's toString() method. Because the ContextStack implements the Map interface Groovy treats it like a Map and does it's own Map printing.

The best solution is to, in general, not print the context or when you need to use ${context.toString()} to call its toString() method explicitly.
