### ISSUE TITLE
Saving deferred ArtifactHits generates NullPointerException

### ISSUE THREAD

**Issue by jenshp** [moqui/moqui-framework#134]
I am loading some data into the default H2 database, that in turn triggers several service calls because of EECAs defined for the tables. All works fine, but after the H2 database is shut down, moqui attempts to add records for ArtifactHits and fails with a NPE.

Right after loading the relevant data (3580 records), I get:
16:01:05.963  WARN l-2-thread-1 .moqui.i.c.ExecutionContextFactoryImpl Deferred ArtifactHit create queue size 10606 is greater than max creates per chunk 1000

And after looking into all other data files with no relevant error (only one exception about an index creation failing because it already existed), I get following entries in the log:

16:01:06.059  INFO         main                              o.m.Moqui Loaded [3580] records in 10 seconds.
16:01:06.099  INFO         main .moqui.i.c.ExecutionContextFactoryImpl ArtifactHitBins stored
16:01:06.100  INFO         main .moqui.i.c.ExecutionContextFactoryImpl Scheduled executor pool shut down
16:01:06.101  INFO         main .moqui.i.c.ExecutionContextFactoryImpl Worker pool shut down
16:01:06.102  INFO         main .moqui.i.c.ExecutionContextFactoryImpl Destroying ToolFactory: SubEthaSmtp
16:01:06.102  INFO         main                     o.s.s.s.SMTPServer SMTP server *:2525 stopping
16:01:06.103  INFO hread *:2525           o.subethama.s.s.ServerThread SMTP server *:2525 stopped
16:01:06.105  INFO         main     o.moqui.i.t.SubEthaSmtpToolFactory SubEtha SMTP server stopped
16:01:06.108  INFO         main .moqui.i.c.ExecutionContextFactoryImpl Destroying ToolFactory: H2Server
16:01:06.108  INFO         main .moqui.i.c.ExecutionContextFactoryImpl Destroying ToolFactory: MCache
16:01:06.110  INFO         main .moqui.i.c.TransactionInternalBitronix Shutting down Bitronix
16:01:06.110  INFO l-2-thread-1      o.moqui.i.c.TransactionFacadeImpl Stashed connection found but transaction is not active (No Transaction (6)) for group transactional: Group: transactional, Con: a ConnectionJavaProxy of a JdbcPooledConnection from datasource transactional_DS in state ACCESSIBLE with usage count 1 wrapping xads1: conn2: url=jdbc:h2:/home/jhp/moqui/fotomax/runtime/db/h2/moqui user=SA on conn3: url=jdbc:h2:/home/jhp/moqui/fotomax/runtime/db/h2/moqui user=SA
16:01:06.111  WARN l-2-thread-1      o.moqui.i.c.TransactionFacadeImpl Transaction not rolled back, status is STATUS_NO_TRANSACTION
16:01:06.112  WARN         main          b.tm.r.j.JdbcPooledConnection close connection with usage count > 0, a JdbcPooledConnection from datasource transactional_DS in state ACCESSIBLE with usage count 1 wrapping xads1: conn2: url=jdbc:h2:/home/jhp/moqui/fotomax/runtime/db/h2/moqui user=SA
16:01:06.112 ERROR l-2-thread-1 .moqui.i.c.ExecutionContextFactoryImpl Error saving ArtifactHits, retrying (5)
java.lang.NullPointerException: null
	at org.moqui.impl.context.TransactionFacadeImpl.commit(TransactionFacadeImpl.groovy:369) ~[moqui.war:2.0.0]
	at org.moqui.impl.context.TransactionFacadeImpl.commit(TransactionFacadeImpl.groovy:363) ~[moqui.war:2.0.0]
	at org.moqui.impl.context.TransactionFacadeImpl.runUseOrBegin(TransactionFacadeImpl.groovy:171) ~[moqui.war:2.0.0]
	at org.moqui.impl.context.ExecutionContextFactoryImpl$DeferredHitInfoFlush.flushQueue(ExecutionContextFactoryImpl.groovy:1186) [moqui.war:2.0.0]
	at org.moqui.impl.context.ExecutionContextFactoryImpl$DeferredHitInfoFlush.run(ExecutionContextFactoryImpl.groovy:1158) [moqui.war:2.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
16:01:06.117 ERROR l-2-thread-1 .moqui.i.c.ExecutionContextFactoryImpl Error saving ArtifactHits, retrying (5)
java.lang.NullPointerException: null
	at org.moqui.impl.context.TransactionFacadeImpl.begin(TransactionFacadeImpl.groovy:312) ~[moqui.war:2.0.0]
	at org.moqui.impl.context.TransactionFacadeImpl.runUseOrBegin(TransactionFacadeImpl.groovy:164) ~[moqui.war:2.0.0]
	at org.moqui.impl.context.ExecutionContextFactoryImpl$DeferredHitInfoFlush.flushQueue(ExecutionContextFactoryImpl.groovy:1186) [moqui.war:2.0.0]
	at org.moqui.impl.context.ExecutionContextFactoryImpl$DeferredHitInfoFlush.run(ExecutionContextFactoryImpl.groovy:1158) [moqui.war:2.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]

It keeps retrying until I finish the execution.

**Comment by jenshp** [comment]
I have been trying to create a reproducible example, but failed to even reproduce the original case... feel free to close this issue if there is no obvious bug to fix.

**Comment by jonesde** [comment]
I made a couple quick changes in commit #6716e0f that should help with this (waiting for the worker pool and executor to shut down, not stopping the H2 server when ToolFactory destroyed).

**Comment by jonesde** [comment]
These changes should help, especially on busier production servers when the app is stopped, but yeah this is a fairly rare case. This did remind me of another one with ElasticSearch when running tests sometimes it would lose index requests because of no wait for them to finish on destroy so looking into that again. Anyway, there may have been a real issue here and this should fix it.
