### ISSUE TITLE
IndexOutofboundsException when put tree under a standalone screen

### ISSUE THREAD

**Issue by chunlinyao** [moqui/moqui-framework#191]
It is thrown from `sri.getActiveScreenDef()`. It seems ScreenTree.getChildNodes is called by `recursiveRunTransition`. `recursiveRunTransition` is against `screenPathDefList`, the `screenPathIndex` will count up by `screenPathDefList`, so `screenUrlInfo.screenRenderDefList.get(screenPathIndex)` in `getActiveScreenDef()` thrown a exception. I did a simple test, call `getActiveScreenDef` in a transition under standalone screen thrown the same Exception.

```

java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_45]
        at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_45]
        at org.moqui.impl.screen.ScreenRenderImpl.getActiveScreenDef(ScreenRenderImpl.groovy:873) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenUrlInfo.getScreenUrlInfo(ScreenUrlInfo.groovy:134) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenRenderImpl.buildUrlInfo(ScreenRenderImpl.groovy:1086) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenRenderImpl.makeUrlByType(ScreenRenderImpl.groovy:1107) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenTree.getChildNodes(ScreenTree.groovy:115) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenTree.sendSubNodeJson(ScreenTree.groovy:74) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenDefinition$ActionsTransitionItem.run(ScreenDefinition.groovy:801) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:239) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:233) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:233) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:233) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:233) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenRenderImpl.recursiveRunTransition(ScreenRenderImpl.groovy:233) ~[moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenRenderImpl.internalRender(ScreenRenderImpl.groovy:356) [moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.screen.ScreenRenderImpl.render(ScreenRenderImpl.groovy:145) [moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.moqui.impl.webapp.MoquiServlet.service(MoquiServlet.groovy:91) [moqui-framework-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT]
 
```

**Comment by jonesde** [comment]
In a way this is a bug, but supporting this is really an enhancement as the getActiveScreenDef() and the other SRI.getActiveScreen* methods are not meant to be called in transitions, always-actions, or pre-actions. There was partial support for calling these in transitions, but not at all in always- or pre-actions.

I started working on the changes, and like the direction as using the screenPathIndex instead of iterators is better in a few ways, and can simplify some code too.

**Comment by jonesde** [comment]
A solution to this and a few related improvements are in commit #cf1eddc.
