### ISSUE TITLE
Error when loading data

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/moqui-framework#222]
I got an error below when I run gradle load. My database is postgres.

 Creating ElasticSearch index hm_wiki_page for HmWikiPage with alias hivemind and adding document mapping
--- 2017-06-20 14:13:25.260 [   RequireNewTx] ERROR                   org.moqui.impl.actions.XmlAction []
 Error running groovy script ([hivemind/pc3Y5ZEgT8Goo7VQKwmLqQ] InvalidAliasNameException[Invalid alias name [hivemind], an index exists with the same name as the alias]):
1 : import static org.moqui.util.ObjectUtilities.*
2 : import static org.moqui.util.CollectionUtilities.*
3 : import static org.moqui.util.StringUtilities.*
4 : import java.sql.Timestamp
5 : // these are in the context by default: ExecutionContext ec, Map<String, Object> context, Map<String, Object> result
6 :     startTime = (System.currentTimeMillis())
7 :     dfDocList_xafind = ec.entity.find("moqui.entity.feed.DataFeedDocument").useCache(true)
8 :             .condition((org.moqui.entity.EntityCondition) ec.entity.conditionFactory.makeActionConditionDirect("dataFeedId", "equals", dataFeedId, null, null, false, false, false, "false"))
9 :             dfDocList = dfDocList_xafind.list()
10 :     documentsIndexed = (0)
11 :
12 :     // begin inline script
13 :     import org.moqui.context.ExecutionContext
14 :                 import org.moqui.elasticsearch.ElasticSearchUtil
15 :                 import java.util.concurrent.Future
16 :
17 :                 ExecutionContext ec = context.ec
18 :                 for (Map dfDoc in dfDocList) {
19 :                     ArrayList<Map> documentList = ec.entity.entityDataDocument.getDataDocuments(dfDoc.dataDocumentId, null, fromUpdateStamp, thruUpdatedStamp)
20 :                     if (!documentList) continue
21 :                     // make sure the index exists
22 :                     ElasticSearchUtil.checkCreateIndex((String) documentList.get(0).get("_index"), ec)
23 :
24 :                     // index the documents
25 :                     int docListSize = documentList.size()
26 :                     // NOTE: doing multiple threads doesn't make a big difference, the bulk indexing makes a huge difference, so effectively disabling this in the if expression
27 :                     if (false) {
28 :                         int numThreads = Runtime.getRuntime().availableProcessors() / 2
29 :                         ec.logger.info("Indexing ${docListSize} type ${dfDoc.dataDocumentId} documents for feed ${dataFeedId} with ${numThreads} threads")
30 :                         int subListSize = docListSize / numThreads
31 :                         ArrayList<Future> futureList = new ArrayList<>(numThreads)
32 :                         for (int i = 0; i < numThreads - 1; i++) {
33 :                             futureList.add(ec.service.async().name("org.moqui.search.SearchServices.index#DataDocuments")
34 :                                     .parameter("documentList", documentList.subList(i * subListSize, (i + 1) * subListSize))
35 :                                     .parameter("verifyIndexes", false)
36 :                                     .callFuture())
37 :                         }
38 :                         futureList.add(ec.service.async().name("org.moqui.search.SearchServices.index#DataDocuments")
39 :                                 .parameter("documentList", documentList.subList((numThreads-1) * subListSize, docListSize))
40 :                                 .parameter("verifyIndexes", false)
41 :                                 .callFuture())
42 :                         for (Future future in futureList) future.get()
43 :                     } else {
44 :                         ec.logger.info("Indexing ${docListSize} type ${dfDoc.dataDocumentId} documents for feed ${dataFeedId}")
45 :                         ec.service.sync().name("org.moqui.search.SearchServices.index#DataDocuments").parameter("documentList", documentList).call()
46 :                     }
47 :                     documentsIndexed += documentList.size()
48 :                 }
49 :     // end inline script
50 :     ec.logger.log("info", """Indexed ${documentsIndexed} documents for feed ${dataFeedId} in ${System.currentTimeMillis() - startTime}ms""", null)
51 :     ec.message.addMessage(ec.resource.expand('''Indexed ${documentsIndexed} documents for feed ${dataFeedId} in ${System.currentTimeMillis() - startTime}ms''',''))
52 : // make sure the last statement is not considered the return value
53 : return;

--- 2017-06-20 14:13:25.260 [   RequireNewTx] WARN        org.moqui.impl.context.TransactionFacadeImpl []
 Transaction set rollback only. The rollback was originally caused by: Error running service org.moqui.search.SearchServices.index#DataFeedDocuments (Throwable)
org.elasticsearch.indices.InvalidAliasNameException: Invalid alias name [hivemind], an index exists with the same name as the alias
        at org.elasticsearch.cluster.metadata.AliasValidator.validateAlias(AliasValidator.java:100) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.metadata.MetaDataIndexAliasesService.lambda$innerExecute$2(MetaDataIndexAliasesService.java:134) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.metadata.AliasAction$Add.apply(AliasAction.java:113) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.metadata.MetaDataIndexAliasesService.innerExecute(MetaDataIndexAliasesService.java:157) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.metadata.MetaDataIndexAliasesService$1.execute(MetaDataIndexAliasesService.java:91) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:633) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:611) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:570) ~[elasticsearch-5.4.1.jar:5.4.1]

**Comment by zhangwei1979** [comment]
Sorry, I should run gradle cleanAll before load
