### ISSUE TITLE
Error when rendering a screen, It may caused by null in hitTimeList retrived from tarpitHitCache

### ISSUE THREAD

**Issue by chunlinyao** [moqui/moqui-framework#239]
I got an error when render a screen today, after 10 minutes it can be opened again. This is the error log
```
org.moqui.impl.screen.ScreenRenderImpl []
 Error rendering screen [component://Sen/screen/SenRoot/app/s/Receive/Receive.xml]
java.lang.NullPointerException: null
        at org.codehaus.groovy.runtime.typehandling.LongMath.subtractImpl(LongMath.java:41) ~[groovy-2.4.12.jar:2.4.12]
        at org.codehaus.groovy.runtime.typehandling.NumberMath.subtract(NumberMath.java:60) ~[groovy-2.4.12.jar:2.4.12]
        at org.codehaus.groovy.runtime.dgmimpl.NumberNumberMinus.minus(NumberNumberMinus.java:43) ~[groovy-2.4.12.jar:2.4.12]
        at org.moqui.impl.context.ArtifactExecutionFacadeImpl.checkTarpit(ArtifactExecutionFacadeImpl.groovy:492) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.context.ArtifactExecutionFacadeImpl.isPermitted(ArtifactExecutionFacadeImpl.groovy:270) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.context.ArtifactExecutionFacadeImpl.pushInternal(ArtifactExecutionFacadeImpl.groovy:90) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenDefinition.render(ScreenDefinition.groovy:479) ~[moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenRenderImpl.renderSubscreen(ScreenRenderImpl.groovy:966) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
        at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1487) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:69) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.MethodCall._eval(MethodCall.java:65) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Expression.eval(Expression.java:81) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:96) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.DollarVariable.accept(DollarVariable.java:59) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.visit(Environment.java:362) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.invoke(Environment.java:714) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.invokeNodeHandlerFor(Environment.java:626) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.recurse(Environment.java:824) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.RecurseNode.accept(RecurseNode.java:73) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.visit(Environment.java:362) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.invoke(Environment.java:714) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.invokeNodeHandlerFor(Environment.java:626) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.recurse(Environment.java:824) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.RecurseNode.accept(RecurseNode.java:73) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.visit(Environment.java:362) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.invoke(Environment.java:714) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.invokeNodeHandlerFor(Environment.java:626) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.VisitNode.accept(VisitNode.java:71) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.visit(Environment.java:326) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.visit(Environment.java:332) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.Environment.process(Environment.java:305) [freemarker-2.3.26-incubating.jar:2.3.26]
        at org.moqui.impl.screen.ScreenWidgets.render(ScreenWidgets.groovy:40) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenSection.renderSingle(ScreenSection.groovy:139) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenSection.render(ScreenSection.groovy:112) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenDefinition.render(ScreenDefinition.groovy:493) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at org.moqui.impl.screen.ScreenRenderImpl.renderSubscreen(ScreenRenderImpl.groovy:966) [moqui-framework-2.1.0-rc2.jar:2.1.0-rc2]
        at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
        at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1487) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:69) [freemarker-2.3.26-incubating.jar:2.3.26]
        at freemarker.core.MethodCall._eval(MethodCall.java:65) [freemarker-2.3.26-incubating.jar:2.3.26]

```

`ArtifactExecutionFacadeImpl.groovy:490~493` is somthing like this:
```
for (int htlInd = 0; htlInd < hitTimeListCopy.size(); htlInd++) {
           Long hitTime = (Long) hitTimeListCopy.get(htlInd)
           if ((hitTime - checkTime) < maxHitsDuration) hitsInDuration++
}
```
Because `checkTime` is from `System.currentTimeMillis()`, I think the hitTime is null. But I can't understand in which situation the hitTimeList will contains a null.

**Comment by jonesde** [comment]
I added a null check. It is weird that it comes back null, but there is a possible explanation even if the code never puts null values in it and that is the concurrency issues with unsynchronized collections like ArrayList. In this case I don't think it's work adding synchronization overhead, ignoring nulls won't hurt anything as it is not like some other data in memory that is more critical and we can't just ignore it with little or no real effect.

**Comment by chunlinyao** [comment]
The null may caused by add element from two threads concurrently, `elementData[size++] = e;`, Two threads interleaved after `size++` but before assignment, one thread will skip an index and override another's assignment.  In some situation, add method may throw ArrayIndexOutOfBoundsException, I will create an unit test to confirm this.
