### ISSUE TITLE
Session token required (in moquiSessionToken)

### ISSUE THREAD

**Issue by ashokraman** [moqui/moqui-framework#30]
Built and loaded the demo data the usual way, tried popc of adding to the cart and then logging in as joe - comes back with this - 
"
_java.lang.IllegalArgumentException: Session token required (in moquiSessionToken) for URL http://localhost:8080/popc/Login/login
	at org.moqui.impl.screen.ScreenRenderImpl.internalRender(ScreenRenderImpl.groovy:297)
	at org.moqui.impl.screen.ScreenRenderImpl.render(ScreenRenderImpl.groovy:158)
	at org.moqui.impl.webapp.MoquiServlet.doScreenRequest(MoquiServlet.groovy:73)
	at org.moqui.impl.webapp.MoquiServlet.doPost(MoquiServlet.groovy:39)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at net.winstone.core.ServletConfiguration.execute(ServletConfiguration.java:270)
	at net.winstone.core.SimpleRequestDispatcher.forward(SimpleRequestDispatcher.java:290)
	at net.winstone.core.listener.RequestHandlerThread.processRequest(RequestHandlerThread.java:212)
	at net.winstone.core.listener.RequestHandlerThread.run(RequestHandlerThread.java:143)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.winstone.util.BoundedExecutorService$1.run(BoundedExecutorService.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
_"
Replaced framework with the latest from github but still get the same error. Need further investigation but thought I would post it in any case.
Thank you,

**Comment by jonesde** [comment]
If you see this in an application it is an error in that application, not in Moqui Framework. Moqui now requires a session token to be passed with web request to screen transitions that involve sending data, with certain exceptions if configured in a screen definition.

If this is in POP Commerce please submit an issue in moqui/PopCommerce here on GitHub, and please mention which screen you went to and which button/link you clicked on, along with the version of PopCommerce and moqui-framework you are using (using an older PopCommerce with a newer moqui-framework would cause this problem).
