### ISSUE TITLE
Error when importing data from Tools->Entity->Import->Resource Location

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/moqui-framework#307]
Please try attached file with .csv extension. You will get error below 

org.moqui.BaseException: CSV first line first field [﻿mantle.party.PartyServices.create#Organization] is not a valid entity name or service name
        at org.moqui.impl.entity.EntityDataLoaderImpl$EntityCsvHandler.loadFile(EntityDataLoaderImpl.groovy:790) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
        at org.moqui.impl.entity.EntityDataLoaderImpl.loadSingleFile(EntityDataLoaderImpl.groovy:314) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
        at org.moqui.impl.entity.EntityDataLoaderImpl$_internalRun_closure1.doCall(EntityDataLoaderImpl.groovy:283) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
        at org.moqui.impl.context.TransactionFacadeImpl$_runRequireNew_closure1.doCall(TransactionFacadeImpl.groovy:196) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

[Organizations.csv.txt](https://github.com/moqui/moqui-framework/files/1761152/Organizations.csv.txt)

**Comment by zhangwei1979** [comment]
It is caused by my file has a leading char feff.
