### ISSUE TITLE
moqui-sftp issue

### ISSUE THREAD

**Issue by lightning-pro** [moqui/moqui-framework#396]
As I can't raise issues in moqui-sftp,I raise it here

When I try to run the demo in moqui-sftp, I encounter error as belows
net.schmizz.sshj.sftp.SFTPException: No such file
here is the log
```
10:46:22.363  INFO 5962452-3826           o.moqui.i.c.LoggerFacadeImpl SFTP put message 100000 to path /home/sftp_root/shared/ExampleSftp/Example100000-2019-12-30.json file 100000 charset UTF-8
10:46:22.363  INFO 5962452-3826     n.schmizz.s.t.r.BouncyCastleRandom Generating random seed from SecureRandom.
10:46:22.367  INFO 5962452-3826            n.schmizz.s.t.TransportImpl Client identity string: SSH-2.0-SSHJ_0.27.0
10:46:22.381  INFO 5962452-3826            n.schmizz.s.t.TransportImpl Server identity string: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
10:46:23.584  INFO 5962452-3826       n.schmizz.s.c.c.d.SessionChannel Will request `sftp` subsystem
10:47:08.208  INFO 5962452-3826            n.schmizz.s.t.TransportImpl Disconnected - BY_APPLICATION
10:47:08.209 ERROR 5962452-3826                  o.moqui.i.a.XmlAction Error running groovy script (net.schmizz.sshj.sftp.SFTPException: No such file): 
```

I even created the file by myself in my vm ubuntu server. but it still encounter the error.
When I traced the code , in SFTPFileTransfer.java line 181 isDirectory(remote) checking ,it throw this exception.
the root cause is that in SFTPEngine.java
```
protected FileAttributes stat(PacketType pt, String path)
            throws IOException {
        return doRequest(newRequest(pt).putString(path, sub.getRemoteCharset()))
                .ensurePacketTypeIs(PacketType.ATTRS)
                .readFileAttributes();
    }
```
ensurePacketTypeIs checking fail due to the type of the response is STATUS but not ATTRS,
I am wondering if anybody encounter the same issue or Just my machine's problem

My client machine is Win 10 with a ubuntu server in Oracle VM box and moqui instance is running in Idea in Win10.

**Comment by jonesde** [comment]
What does the full except with stack trace and causes look like? You only included a minor part of the error message: "o.moqui.i.a.XmlAction Error running groovy script (net.schmizz.sshj.sftp.SFTPException: No such file)". There may be more info further down about which file was missing, what threw the exception, etc.

**Comment by lightning-pro** [comment]
Well, the below is the full exception.
I call the service 
moqui.example.ExampleServices.produce#ExampleMessage
in the ServiceRun page with
 Example ID =  100001 
System Message Type ID = ExampleSftp
System Message Remote ID = ExampleSftpLocal
```
10:19:37.948  INFO oquiWorker-2           o.moqui.i.c.LoggerFacadeImpl SFTP put message 100053 to path /home/sftp_root/shared/ExampleSftp/Example100053-2020-01-08.json file 100053 charset UTF-8
10:19:37.949  INFO oquiWorker-2     n.schmizz.s.t.r.BouncyCastleRandom Generating random seed from SecureRandom.
10:19:37.958  INFO oquiWorker-2            n.schmizz.s.t.TransportImpl Client identity string: SSH-2.0-SSHJ_0.27.0
10:19:38.163  INFO oquiWorker-2            n.schmizz.s.t.TransportImpl Server identity string: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
10:19:40.628  INFO oquiWorker-2       n.schmizz.s.c.c.d.SessionChannel Will request `sftp` subsystem
10:19:40.639  INFO oquiWorker-2            n.schmizz.s.t.TransportImpl Disconnected - BY_APPLICATION
10:19:40.641 ERROR oquiWorker-2                  o.moqui.i.a.XmlAction Error running groovy script (net.schmizz.sshj.sftp.SFTPException: No such file): 
1 : import static org.moqui.util.ObjectUtilities.*
2 : import static org.moqui.util.CollectionUtilities.*
3 : import static org.moqui.util.StringUtilities.*
4 : import java.sql.Timestamp
5 : // these are in the context by default: ExecutionContext ec, Map<String, Object> context, Map<String, Object> result
6 :     if (true) {
7 :         org.moqui.entity.EntityValue find_one_result = ec.entity.find("moqui.service.message.SystemMessage")
8 :                 .condition(context).one()
9 :         if (systemMessage instanceof Map && !(systemMessage instanceof org.moqui.entity.EntityValue)) { if (find_one_result) systemMessage.putAll(find_one_result) } else { systemMessage = find_one_result }
10 :     }
11 :     if (systemMessage == null) {
12 :         ec.message.addError(ec.resource.expand('''Could not find SystemMessage with ID ${systemMessageId}''' ?: "Error in actions",''))
13 :     return;
14 :     }
15 : 
16 :     systemMessageType = (systemMessage.'moqui.service.message.SystemMessageType')
17 :     if (systemMessageType == null) {
18 :         ec.message.addError(ec.resource.expand('''System message ${systemMessageId} has no SystemMessageType, not sending.''' ?: "Error in actions",''))
19 :     return;
20 :     }
21 : 
22 :     systemMessageRemote = (systemMessage.'moqui.service.message.SystemMessageRemote')
23 :     if (systemMessageRemote == null) {
24 :         ec.message.addError(ec.resource.expand('''System message ${systemMessageId} has no SystemMessageRemote, not sending.''' ?: "Error in actions",''))
25 :     return;
26 :     }
27 : 
28 : 
29 : // begin inline script
30 : import org.moqui.sftp.SftpClient
31 :                 import java.nio.charset.Charset
32 :                 import java.sql.Timestamp
33 : 
34 :                 Timestamp msgDate = systemMessage.messageDate ?: systemMessage.initDate ?: ec.user.nowTimestamp
35 :                 String sendPath = ec.resource.expand(systemMessageType.sendPath, null,
36 :                         [systemMessageId:systemMessage.systemMessageId, remoteMessageId:systemMessage.remoteMessageId,
37 :                          systemMessageTypeId:systemMessage.systemMessageTypeId, systemMessageRemoteId:systemMessage.systemMessageRemoteId,
38 :                          date:ec.l10n.format(msgDate, "yyyy-MM-dd"), dateTime:ec.l10n.format(msgDate, "yyyy-MM-dd-HH-mm-ss")], false)
39 :                 String filename = systemMessage.remoteMessageId ?: systemMessage.systemMessageId
40 :                 Charset charset = Charset.forName(systemMessageRemote.remoteCharset ?: "UTF-8")
41 : 
42 :                 // use SftpClient to put the file
43 :                 SftpClient sftpClient = new SftpClient((String) systemMessageRemote.sendUrl, (String) systemMessageRemote.username)
44 :                 if (systemMessageRemote.privateKey) sftpClient.publicKeyPkcs8((String) systemMessageRemote.privateKey, (String) systemMessageRemote.publicKey)
45 :                 else sftpClient.password((String) systemMessageRemote.password)
46 : 
47 :                 // if SFTP server doesn't support set file attributes after put/upload
48 :                 if (systemMessageRemote.remoteAttributes == 'N') sftpClient.preserveAttributes(false)
49 : 
50 :                 ec.logger.info("SFTP put message ${systemMessageId} to path ${sendPath} file ${filename} charset ${charset}")
51 :                 sftpClient.connect()
52 :                 try {
53 :                     sftpClient.put(sendPath, filename, (String) systemMessage.messageText, charset)
54 :                 } finally {
55 :                     sftpClient.close()
56 :                 }
57 : // end inline script
58 : // make sure the last statement is not considered the return value
59 : return;
60 : 


10:19:40.641  WARN oquiWorker-2      o.moqui.i.c.TransactionFacadeImpl Transaction rollback. The rollback was originally caused by: Error running service org.moqui.sftp.SftpMessageServices.send#SystemMessageSftp (Throwable)
net.schmizz.sshj.sftp.SFTPException: No such file
	at net.schmizz.sshj.sftp.Response.error(Response.java:140) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.Response.ensurePacketTypeIs(Response.java:117) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPEngine.open(SFTPEngine.java:143) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPEngine.open(SFTPEngine.java:149) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.uploadFile(SFTPFileTransfer.java:233) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.upload(SFTPFileTransfer.java:186) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.access$100(SFTPFileTransfer.java:166) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPFileTransfer.upload(SFTPFileTransfer.java:64) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPClient.put(SFTPClient.java:244) ~[sshj-0.27.0.jar:0.27.0]
	at org.moqui.sftp.SftpClient.put(SftpClient.groovy:209) ~[moqui-sftp-1.0.0.jar:?]
	at org_moqui_sftp_SftpMessageServices_send_SystemMessageSftp.run(org_moqui_sftp_SftpMessageServices_send_SystemMessageSftp:53) ~[?:?]
	at org.moqui.impl.actions.XmlAction.run(XmlAction.java:67) ~[moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.runner.InlineServiceRunner.runService(InlineServiceRunner.java:59) ~[moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.java:307) ~[moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.java:121) ~[moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org_moqui_impl_SystemMessageServices_send_ProducedSystemMessage.run(org_moqui_impl_SystemMessageServices_send_ProducedSystemMessage:48) [script:?]
	at org.moqui.impl.actions.XmlAction.run(XmlAction.java:67) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.runner.InlineServiceRunner.runService(InlineServiceRunner.java:59) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.java:307) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.java:121) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallAsyncImpl$AsyncServiceInfo.runInternal(ServiceCallAsyncImpl.groovy:132) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallAsyncImpl$AsyncServiceRunnable.run(ServiceCallAsyncImpl.groovy:147) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
10:19:40.647  WARN oquiWorker-2      o.moqui.i.c.TransactionFacadeImpl Transaction rollback for [Error running service org.moqui.sftp.SftpMessageServices.send#SystemMessageSftp (Throwable)]. Here is the current location: 
org.moqui.BaseException: Rollback location
	at org.moqui.impl.context.TransactionFacadeImpl.rollback(TransactionFacadeImpl.groovy:445) ~[moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.context.TransactionFacadeImpl.rollback(TransactionFacadeImpl.groovy:421) ~[moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.java:332) ~[moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.java:121) ~[moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org_moqui_impl_SystemMessageServices_send_ProducedSystemMessage.run(org_moqui_impl_SystemMessageServices_send_ProducedSystemMessage:48) [script:?]
	at org.moqui.impl.actions.XmlAction.run(XmlAction.java:67) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.runner.InlineServiceRunner.runService(InlineServiceRunner.java:59) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.java:307) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.java:121) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallAsyncImpl$AsyncServiceInfo.runInternal(ServiceCallAsyncImpl.groovy:132) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallAsyncImpl$AsyncServiceRunnable.run(ServiceCallAsyncImpl.groovy:147) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
10:19:40.649  WARN oquiWorker-2        o.moqui.i.s.ServiceCallSyncImpl Error running service org.moqui.sftp.SftpMessageServices.send#SystemMessageSftp (Throwable) Artifact stack: org.moqui.sftp.SftpMessageServices.send#SystemMessageSftp, org.moqui.impl.SystemMessageServices.send#ProducedSystemMessage
net.schmizz.sshj.sftp.SFTPException: No such file
	at net.schmizz.sshj.sftp.Response.error(Response.java:140) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.Response.ensurePacketTypeIs(Response.java:117) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPEngine.open(SFTPEngine.java:143) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPEngine.open(SFTPEngine.java:149) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.uploadFile(SFTPFileTransfer.java:233) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.upload(SFTPFileTransfer.java:186) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.access$100(SFTPFileTransfer.java:166) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPFileTransfer.upload(SFTPFileTransfer.java:64) ~[sshj-0.27.0.jar:0.27.0]
	at net.schmizz.sshj.sftp.SFTPClient.put(SFTPClient.java:244) ~[sshj-0.27.0.jar:0.27.0]
	at org.moqui.sftp.SftpClient.put(SftpClient.groovy:209) ~[moqui-sftp-1.0.0.jar:?]
	at org_moqui_sftp_SftpMessageServices_send_SystemMessageSftp.run(org_moqui_sftp_SftpMessageServices_send_SystemMessageSftp:53) ~[?:?]
	at org.moqui.impl.actions.XmlAction.run(XmlAction.java:67) ~[moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.runner.InlineServiceRunner.runService(InlineServiceRunner.java:59) ~[moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.java:307) ~[moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.java:121) ~[moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org_moqui_impl_SystemMessageServices_send_ProducedSystemMessage.run(org_moqui_impl_SystemMessageServices_send_ProducedSystemMessage:48) [script:?]
	at org.moqui.impl.actions.XmlAction.run(XmlAction.java:67) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.runner.InlineServiceRunner.runService(InlineServiceRunner.java:59) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.java:307) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.java:121) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallAsyncImpl$AsyncServiceInfo.runInternal(ServiceCallAsyncImpl.groovy:132) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at org.moqui.impl.service.ServiceCallAsyncImpl$AsyncServiceRunnable.run(ServiceCallAsyncImpl.groovy:147) [moqui-framework-3.0.0-rc2.jar:3.0.0-rc2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
10:19:40.653 ERROR oquiWorker-2          o.moqui.i.c.MessageFacadeImpl No such file
```

**Comment by jonesde** [comment]
It looks like the root cause of the exception is the "net.schmizz.sshj.sftp.SFTPException: No such file" thrown by SSHJ so there is an error between the SSHJ client and the SFTP server. If this is related to the ATTR response (usually due to how the SFTP server is configured or lack of support in the SFTP server) you can try setting SystemMessageRemote.remoteAttributes to 'N'.

You can see this on line 48 in the Groovy script generated from the XML Actions where this is implemented, it calls sftpClient.preserveAttributes(false) so SSHJ behaves differently and doesn't try the ATTR stuff.

**Comment by jonesde** [comment]
Any updates on this? If there are no further replies I'll close this for inactivity as it doesn't appear to be a framework issue.

**Comment by lightning-pro** [comment]
oh, sorry that I don't tested it yet, I will do the test later, yes the error is not related to the framework
