### ISSUE TITLE
eleastic search errors at startup like: failed to join {hans-laptop}{Jp2CKyqFSNe-fvk2at91Dw}

### ISSUE THREAD

**Issue by growerp** [moqui/moqui-framework#413]
after standard installation with:

    git clone https://github.com/moqui/moqui-framework.git moqui
    cd moqui
    ./gradlew getComponent -Pcomponent=PopCommerce
    ./gradlew load

i get many messages in the log like:
'''
[2020-04-24T14:00:01,963][INFO ][o.e.c.c.JoinHelper       ] [hans-laptop] failed to join {hans-laptop}{Jp2CKyqFSNe-fvk2at91Dw}{ITfGJLIGQMCRvpHt_VlHpA}{127.0.0.1}{127.0.0.1:9302}{dim} with JoinRequest{sourceNode={hans-laptop}{Jp2CKyqFSNe-fvk2at91Dw}{ITfGJLIGQMCRvpHt_VlHpA}{127.0.0.1}{127.0.0.1:9302}{dim}, optionalJoin=Optional[Join{term=235, lastAcceptedTerm=0, lastAcceptedVersion=0, sourceNode={hans-laptop}{Jp2CKyqFSNe-fvk2at91Dw}{ITfGJLIGQMCRvpHt_VlHpA}{127.0.0.1}{127.0.0.1:9302}{dim}, targetNode={hans-laptop}{Jp2CKyqFSNe-fvk2at91Dw}{ITfGJLIGQMCRvpHt_VlHpA}{127.0.0.1}{127.0.0.1:9302}{dim}}]}
org.elasticsearch.transport.TransportException: transport stopped, action: internal:cluster/coordination/join
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:278) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.4.2.jar:7.4.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
'''

**Comment by jonesde** [comment]
These are log messages from ElasticSearch, nothing to do with Moqui except that the MoquiStart class now streams the logs from the separate process started to the Moqui console output. If you want to discuss it more to ask others to explain how ElasticSearch works you could try the mailing list.

**Comment by hansbak** [comment]
You think that gives new users a good impression? because it is clearly stated they are 'join' error messages? if this is normal, should not these be suppresed?

**Comment by jonesde** [comment]
Those messages are from ElasticSearch, I have zero control or influence over them, and for me even interpreting various messages from ES requires research as I go.

I'm not even sure what you're asking for... are you looking for an explanation of what all of those messages mean? Are you asking for them to be suppressed? Originally I didn't stream the ES logs to the console running Moqui but when Chunlin Yao contributed a few improvements to the stuff for running ES in a parallel process controlled by the Moqui process he included them. For my part it's helpful to see, and without big complaints IMO they should stay.

In your case that could be an error message telling you that ES is not running, but I don't know... there isn't enough in the log snippet you included to see everything that's happening, and while it looks like you have ES 7.4.2 installed in runtime/elasticsearch you didn't mention anything about that in your 'standard installation' steps so I don't know how anything from ElasticSearch would even get in there. From the steps you mentioned Moqui would just complain at startup that it couldn't connect to ES at 'http://127.0.0.1:9200' which is the default location to look for it.

**Comment by hansbak** [comment]
Hi David , i was just concerned about the impression with new users, that should be as smooth as possible?

However after rebooting, starting the moqui system several times first 2 times did not start..., it now starts up ok...could be some old files where there or so, now difficult to see.

So i am fine now. Thanks for your help.
